### ISSUE TITLE
Is this broken in latest Civi?

### ISSUE THREAD

**Issue by edward-peters** [osseed/com.osseed.eventtimezone#7]
Thank you for this wonderful extension.
Unfortunately I cannot get the timezone setting to save when editing an event. 
I am using CiviCRM 5.28.1 and Drupal 8.9.5
Can you advise whether there is an issue?
Thanks so much.
Edward Peters

**Comment by pranav45** [comment]
@edward-peters Have fixed issue under event timezone new release please Visit our latest extension https://github.com/osseed/ind.com.osseed.eventtimezone/releases/tag/1.1

**Comment by edward-peters** [comment]
> @edward-peters Have fixed issue under event timezone new release please Visit our latest extension https://github.com/osseed/ind.com.osseed.eventtimezone/releases/tag/1.1

Thanks very much indeed!

**Comment by edward-peters** [comment]
@pranav45 Unfortunately I am having the same problem with site running Drupal 8.9.14 and CiviCRM 5.36.1. Try as I do, flushing cache multiple times, etc, the selected timezone does not save when I save the event, and just reverts to the default 'Select timezone' in the dropdown.
Is there something I am missing about how to configure this?

**Comment by edward-peters** [comment]
@pranav45 Any chance of a response on this? I can pay you a little if needed, as my client requires this great functionality you have added!

**Comment by osseed** [comment]
@edward-peters Please use https://github.com/osseed/ind.com.osseed.eventtimezone extension (master branch) which have all fixes according to new CiviCRM and Drupal 
Still if you need any help please drop email to hello@osseed.com we will be happy to help you.

JFYI: We are going to delete this repo in few days.
